### ISSUE TITLE
How can I use this template?

### ISSUE THREAD

**Issue by M1saka10010** [lr580/algorithm_template#2]
Your template are so hard that I can't understand it.  So can u help help me? Thank u so much.

**Comment by lr580** [comment]
since this templace is not for beginner, u can learn some basic algorithms first, and after u  become a little more skilled u can try to understand it :)
and noted that template is summary rather than tutorial, in other word u can understand the content only if you've learned it before

**Comment by M1saka10010** [comment]
The king of algorithm has updated many new features again. I bow down in admiration!
